export const metadata = {
    title: "Novel in vitro and in vivo protocols",
    description: '',
}

export default function inVivoProtocols() {
    return (
        <>
            <h1>The RummerLab</h1>
            <p>Potential students, a little advice…</p>
            <p>Prof. Scott Keogh has compiled an excellent list of resources and advice for students and postdoctoral fellows <a href="http://biology.anu.edu.au/hosted_sites/Scott/Resources-and-advice.html">here</a>. And if you're about to contact me to inquire about graduate school (MSc, PhD), check <a href="http://sciencecareers.sciencemag.org/career_magazine/previous_issues/articles/2015_05_06/caredit.a1500118">this</a> out!</p>

            <h2>Current post-docs</h2>
            <p>Dr. Björn Illing I am originally from Germany, where I earned my diploma (2009) at the University of Hamburg conducting eco-morphological research on spawning aggregations of a temperate clupeid fish species. I switched work groups after that and got fascinated by the early life stages of fish and how ecological and physiological aspects determine their survival in the oceans. I finished my doctoral studies (2016) on how environmental stressors affect the growth, condition and survival of Atlantic herring offspring at the University of Hamburg, working in parallel at a federal German research institute developing a novel hyperbaric swimming flume for testing fish species during extended oceanic spawning migrations. Now, I have finally made it to warmer waters and spend time in the Rummer lab investigating the effects of environmental stressors on coral reef fish larvae. I am funded, in part, by the <a href="http://www.biologists.com/">Company of Biologists</a>. Find me on <a href="https://www.researchgate.net/profile/Bjoern_Illing">ResearchGate</a> and on <a href="https://twitter.com/Bjoern_Illing">Twitter</a></p>

            <h2>Current PhD students</h2>
            <p><strong>Sybille Hess</strong> I am originally from Switzerland but did my MSc here at JCU with Drs Jodie Rummer & Amelia Wenger. I recently started my PhD here at JCU with Dr Rummer, and Drs Andy Hoey & Amelia Wenger are my co-supervisors. I am interested in the effects of human activities on coral reefs, especially on reef fishes. My PhD research investigates how poor water quality (e.g., increasing levels of suspended sediments) affects fish metabolic performance, the consequences this may have for important activities such as swimming, and how this may translate into changes in fish community structure. I am working primarily with fish larvae and juveniles, and combine lab-based and field experiments to tackle these questions. You can also find me on <a href="https://twitter.com/HessSybille">Twitter</a>. Email: <a href="mailto:sybille.hess@my.jcu.edu.au">sybille.hess@my.jcu.edu.au​</a> Check out my recent paper <a href="http://www.nature.com/articles/srep10561">"Exposure of clownfish larvae to suspended sediment levels found on the Great Barrier Reef: Impacts on gill structure and microbiome"</a> , which was published in Scientific Reports.</p>
            <p><strong>Tiffany Nay</strong> I earned my BSc in Marine Biology from the University of West Florida while spending the summers in Wakatobi, Southeast Sulawesi, Indonesia assisting research on how crab-eating frogs and mudskipper fishes tolerate water loss and estimating metabolic rates in sea snakes. I earned my MSc here at JCU, and my research investigated how/why fish utilize microhabitats with fluctuating water quality in coral reefs and mangrove ecosystems.  I just started my PhD this month expanding upon my interests in microhabitat use and am supervised by Drs. Rummer, Hoey, and Johansen. You can also find me on <a href="https://twitter.com/TiffanyJNay">Twitter</a>. Email: <a href="mailto:tiffany.nay@my.jcu.edu.au">tiffany.nay@my.jcu.edu.au</a> Check out my recent paper <a href="http://br9xy4lf5w.scholar.serialssolutions.com/?sid=google&amp;auinit=TJ&amp;aulast=Nay&amp;atitle=Behavioural+thermoregulation+in+a+temperature-sensitive+coral+reef+fish,+the+five-lined+cardinalfish+(Cheilodipterus+quinquelineatus)&amp;id=doi:10.1007/s00338-015-1353-4&amp;title=Coral+reefs&amp;volume=34&amp;issue=4&amp;date=2015&amp;spage=1261&amp;issn=0722-4028">"</a><a href="http://br9xy4lf5w.scholar.serialssolutions.com/?sid=google&amp;auinit=TJ&amp;aulast=Nay&amp;atitle=Behavioural+thermoregulation+in+a+temperature-sensitive+coral+reef+fish,+the+five-lined+cardinalfish+(Cheilodipterus+quinquelineatus)&amp;id=doi:10.1007/s00338-015-1353-4&amp;title=Coral+reefs&amp;volume=34&amp;issue=4&amp;date=2015&amp;spage=1261&amp;issn=0722-4028">Behavioural thermoregulation in a temperature-sensitive coral reef fish, the five-lined cardinalfish (Cheilodipterus quinquelineatus)"</a>, which was published in the journal, Coral Reefs.</p>
            <p><strong>Ian Bouyoucos</strong> Originally from New York, I completed my B.Sc. at the University of Michigan, and my M.Sc. at the University of Illinois under the supervision of Dr. Cory Suski. For my Master's thesis, I investigated the daily energy requirements of juvenile lemon sharks (Negaprion brevirostris) in relation to the energetic costs of fishing capture. For my PhD, I am investigating the capacity for juvenile blacktip (Carcharhinus melanopterus) and lemon sharks (N. acutidens) to balance processes related to energy expenditure and acquisition while managing stressors across a range of environmental conditions in nursery habitats around Moorea, French Polynesia. In addition to Dr. Rummer, I am supervised by Dr. Colin Simpfendorfer. Find me on <a href="https://scholar.google.com/citations?user=NEZ4oyIAAAAJ&amp;hl=en&amp;oi=ao">Google Scholar</a>, see my <a href="https://ianbouyoucos.wordpress.com/">online CV</a>, and follow me on <a href="https://twitter.com/Bouyoucos">Twitter</a>. There, you can check out <a href="https://twitter.com/hashtag/physioshark?src=hash">#physioshark</a> to follow the shark conservation physiology action in Moorea! E-mail: <a href="mailto:ian.bouyoucos@my.jcu.edu">ian.bouyoucos@my.jcu.edu</a></p>
            <p>Carolyn Wheeler I am originally from New York, and completed my BS in Marine Science at the University of New England in Maine. My undergraduate honor's thesis focused on determining sex and maturity of Atlantic sturgeon using non-lethal techniques. Check out my latest paper <a href="https://academic.oup.com/conphys/article/4/1/cow059/2660837/Using-circulating-reproductive-hormones-for-sex?searchresult=1">here</a>! Additionally during this time, I collaborated with the University of Miami to study the reproductive biology of tiger sharks at an aggregation site in the Bahamas. These projects piqued my interest in fish physiology. For my PhD, I am be co-advised by Drs Jodie Rummer and John Mandelman at the New England Aquarium in Boston where my research will occur. My research aims to evaluate how ocean warming will impact epaulette shark development, survival, and post-hatch physiological performance. You can also follow me on <a href="https://twitter.com/Wheel_House23">Twitter</a> and <a href="https://www.researchgate.net/profile/Carolyn_Wheeler">ResearchGate</a>.                                                           Email: <a href="mailto:carolyn.wheeler23@gmail.com">carolyn.wheeler23@gmail.com</a></p>
            <p>Kelly Hannan ... Email: <a href="mailto:kelly.hannan@my.jcu.edu.au">kelly.hannan@my.jcu.edu.au</a></p>
            <p>Sofia Jane-Schlaepfer ... Email: <a href="mailto:sofia.jainschlaepfer@my.jcu.edu.au">sofia.jainschlaepfer@my.jcu.edu.au</a></p>
            <p>Taryn Laubenstein I am originally from Massachusetts, and earned my BS in Ecology and Evolutionary Biology from Yale University.  In my senior year I completed my thesis on the effect of temperature on larval development and parental care in a Mediterranean fish.  At JCU, working with Dr. Rummer and my primary advisor Dr. Philip Munday, I am investigating the tradeoffs between behavioural and physiological tolerance to increased carbon dioxide levels (ocean acidification) in reef fishes. Follow me on <a href="https://twitter.com/ScienceTaryn">Twitter</a>. Email: <a href="mailto:taryn.laubenstein@my.jcu.edu.au">taryn.laubenstein@my.jcu.edu.au</a></p>
            <p>Adam Downie I am from Canada, where I earned my BSc in marine biology (first class honours) at the University of New Brunswick, Saint John campus where I worked in <a href="http://www.unb.ca/saintjohn/sase/research/kiefferlab/">Dr. Jim Kieffer's lab</a> investigating the eco-physiology of sturgeon. My honours thesis focused on the physiological responses of juvenile shortnose sturgeon following an acute seawater challenge. After graduation, I continued my work on salinity tolerance (as a research technician for Dr. Kieffer) and studied substrate preference and swimming in juvenile sturgeon.  During this time, I mentored an undergraduate and honours thesis student.  Outside of the lab, I held a seat on the local Animal Care Committee during my undergraduate degree. I returned to JCU (I studied in Australia through UNB's Study Abroad Program) to intern in the Rummer Lab, and specifically to work with Sybille Hess' PhD research, but now I'm commencing my own PhD research where I will look at the development of athletic performance in coral reef fishes. Email: <a href="mailto:adam2283@live.com">adam2283@live.com</a></p>

            <h2>Current MSc students</h2>
            <p>Eva Jacquesson (based at <a href="http://www.criobe.pf/">Centre de Recherche Insulaire et Observatoire de </a><a href="http://www.criobe.pf/">l'Environnement (CRIOBE)</a> Papetoai, Moorea, Polynésie française) ... Email: <a href="mailto:eva.jacquesson@gmail.com">eva.jacquesson@gmail.com</a></p>
            <p>Monica Morin I am originally from Massachusetts, and earned my BS in Marine Science from the University of New England in Maine. My senior research focused on ecosystem based modeling to determine carrying capacity of bivalve aquaculture. I have been interested in the impacts climate change has on our marine ecosystems, and I will be working with Dr. Rummer to determine how these impacts will effect the future of reef fish in coral reef systems.  Email: <a href="mailto:morinmonica12@gmail.com">morinmonica12@gmail.com</a></p>
            <p>Leteisha Prescott   Email: <a href="mailto:leteisha.prescott@my.jcu.edu.au">leteisha.prescott@my.jcu.edu.au ​</a> I am originally from the Sunshine Coast, but completed my undergraduate degree here at JCU. Since late 2015, I have been an intern in Dr. Jodie Rummer’s lab, where I have been working closely with Sybille Hess (PhD candidate) investigating how suspended sediments can impair oxygen uptake in coral reef fishes. I am now starting my Master’s research with Drs. Jodie Rummer and Naomi Gardiner. Specifically, I am examining the gills of coral reef fishes in hopes of understanding the changes they make when they experience increased temperatures during a coral bleaching event. Follow me on <a href="https://twitter.com/TeishPrescott">Twitter</a> and the new <a href="https://t.co/f7ugPD3HTs">RummerLab Instagram</a> page to keep up-to-date with what is happening in our lab.</p>
            
            <h2>Honours</h2>
            <p><strong>Dare Lawrence</strong> My interests are in heavy metal accumulation in fish that are ecologically and commercially important. My research spans the North Queensland Coast and inland parts of the Great Barrier Reef. I am co-supervised by Dr. Rummer and Dr. Angela Capper. Email: <a href="mailto:dare.lawrence@my.jcu.edu.au">dare.lawrence@my.jcu.edu.au</a></p>


            <h2>Undergraduates and student collaborations</h2>
            <p><strong>Lauren Nadler</strong> (PhD student) Originally from the USA, I completed my undergraduate studies in marine science at Boston University before moving to Glasgow, Scotland for a Master of Research degree.  For my PhD at JCU, I am studying the potential impacts of climate change on schooling behaviour in coral reef fish. Email: <a href="mailto:lauren.nadler@my.jcu.edu.au">lauren.nadler@my.jcu.edu.au</a> Website: <a href="http://laurenenadler.weebly.com">http://laurenenadler.weebly.com</a></p>
            <p>Floriaan Devloo-Delva (The Belgian volunteer) I followed an Erasmus Mundus in Marine Biodiversity and Conservation at the universities of Ghent (Belgium), Algarve (Portugal) and Oviedo (Spain). I finished this master in June with highest distinction. I am currently in the process of publishing my thesis “The ecological and genetic characterisation of an invasive mussel (Xenostrobus securis) in Northern Spain”.  I was also privileged to present this topic on the YOUMARES 2015 conference in Bremen (Germany). Now I am traveling in order to gain some more experience and looking into possible PhD positions. I am truly passionate about shark research and conservation. That is how I ended up in the Rummer lab, feeding the amazing epaulette sharks. You can also find me on <a href="https://twitter.com/FloriaanDD">Twitter</a>. Email: <a href="mailto:floriaan.devloo.delva@hotmail.com">floriaan.devloo.delva@hotmail.com</a></p>

            <h2>Technical Staff</h2>
            <p><strong>Nao Nakamura</strong> (laboratory and field technician, based at <a href="http://www.criobe.pf/">Centre de Recherche Insulaire et Observatoire de </a><a href="http://www.criobe.pf/">l'Environnement (CRIOBE)</a> Papetoai, Moorea, Polynésie française)   I am originally from Japan, but I grew up in France where I completed my MSc (Hons) at Toulouse, Paul Sabatier University.  I specialized in animal behavior, cognition and neurosciences. During this year, I studied the sensory capacity of the clownfish toward different water cues and used histological protocols to measure different parts of brain involved in recognition. I have since been employed by CRIOBE in Moorea, French Polynesia as a research assistant (both field and laboratory) and work on many subjects including: PCC (post-larvae capture and culture, catching fish by crest net and by light-trap), fish behaviour, coral larvae behaviour, annual monitoring of juveniles lemon and black tip reef shark populations, scientific diving to record lemon shark behaviour, annual monitoring of glass eel population, etc. I have also been working with Dr. Rummer on her ongoing project -- #physioshark -- as a field and laboratory assistant focusing on blood sampling and analyses. Email: <a href="mailto:nao.nakamura34@gmail.com">nao.nakamura34@gmail.com​</a></p>

            <h2>Alumni</h2>
            <p><strong>Ian McLeod</strong> (PhD - 2014) I am currently employed as a Senior Research Scientist at TropWATER, James Cook University. My research focusses on coastal repair, sportsfishing and ecotourism, coral reef ecology, climate change impacts on the marine environment and land-based effects on coastal waters. I am the Business and Innovation Manager for TropWATER and Co-founder and Director of Cinematic Science (<a href="http://www.cinematicscience.com/">www.CinematicScience.com</a>), a production company that uses professional cinematic techniques and socially innovative campaigns to tell unique science-based stories. During my Postdoctoral years (2014-15) I had the privilege of working on the wild rivers of Papua New Guinea investigating how sportfishing tourism could benefit people and the environment. Learn more about this research at <a href="http://www.niuginiblackbass.com/">www.Niuginiblackbassresearch.com</a>. During my PhD I had the great pleasure of collaborating with and being mentored by Dr Rummer while I researched climate change impacts on coral reef fish populations from ecophysiological to macroecological scales.  Email: <a href="mailto:ian.mcleod1@jcu.edu.au">ian.mcleod1@jcu.edu.au</a> ResearchGate: <a href="https://www.researchgate.net/profile/Ian_Mcleod4">https://www.researchgate.net/profile/Ian_Mcleod4</a> Twitter: <a href="https://twitter.com/DrIanMcLeod">@DrIanMcLeod</a></p>
            <p><strong>Dennis Heinrich</strong> (Honours, 1st class - 2013) Email: <a href="mailto:dennis.heinrich@my.jcu.edu.au">dennis.heinrich@my.jcu.edu.au</a><a href="mailto:dennis.heinrich@my.jcu.edu.au"> </a><a href="mailto:liss.bowden@csiro.au"> </a>  <a href="mailto:liss.bowden@csiro.au"> </a> <a href="mailto:liss.bowden@csiro.au">  </a>  I earned my Honour's at James Cook University under the supervision of Dr Jodie Rummer, <a href="https://research.jcu.edu.au/portfolio/philip.munday">Prof. Philip Munday</a>, <a href="https://research.jcu.edu.au/portfolio/colin.simpfendorfer/">Prof. Colin Simpfendorfer</a>, and <a href="https://research.jcu.edu.au/cstfa/people/staff/dr-michelle-heupel">Dr Michelle Heupel</a> where I focused on understanding how near future ocean acidification conditions could affect a benthic coral reef associated shark, the epaulette shark.  Check out my first paper:  <a href="http://conphys.oxfordjournals.org/content/2/1/cou047.abstract">"A product of its environment: the epaulette shark (Hemiscyllium ocellatum) exhibits physiological tolerance to elevated environmental CO2"</a>, which was published in Conservation Physiology. Check out my second paper: <a href="http://icesjms.oxfordjournals.org/content/early/2015/05/07/icesjms.fsv085.abstract">"Foraging behaviour of the epaulette shark (Hemiscyllium ocellatum) is not affected by elevated CO2"</a>, which was published in ICES Journal of Marine Science I am starting a PhD in March 2016 with <a href="http://southernsharkecologygroup.com/publications/charlie-huveneers/">Dr. Charlie Huveneers</a> and the <a href="http://southernsharkecologygroup.com/publications/charlie-huveneers/">Southern Shark Ecology Group</a> at Flinders University in Adelaide.</p>
            <p><strong>Alyssa Bowden</strong> (MSc, High Distinction - 2013) Email: <a href="mailto:liss.bowden@csiro.au">liss.bowden@csiro.au</a><a href="mailto:liss.bowden@csiro.au">   </a>   I earned my BSc in Marine Biology from the University of North Carolina at Wilmington and my MSc in Marine Biology from James Cook University in Townsville, Queensland where I focused on gill remodelling in tropical reef fish as a result of elevated temperatures.  Check out my first publication: <a href="http://www.sciencedirect.com/science/article/pii/S1095643314001068">"Alterations in gill structure in tropical reef fishes as a result of elevated temperatures"</a>, which was published in Comparative Biochemistry and Physiology A. Currently I am working on my PhD at the University of Tasmania studying the physiological consequences of amoebic gill disease in Atlantic salmon with <a href="http://www.utas.edu.au/zoology/research/comparative-endocrinology-and-ecophysiology/physiological-monitoring-of-atlantic-salmon-salmo-salar-under-aquaculture-conditions/peter-frappell">Prof. Peter Frappell</a>, <a href="http://www.csiro.au/Organisation-Structure/Flagships/Food-Futures-Flagship/FFF_People/Morash-Andrea.aspx">Dr Andrea Morash</a>, and <a href="http://www.csiro.au/Organisation-Structure/Flagships/Food-Futures-Flagship/FFF_People/AndrewarthaSarah-FFF-Profile.aspx">Dr Sarah Andrewartha</a>.</p>
            <p><strong>Sybille Hess</strong> (MSc, High Distinction - 2014) My research interests are human impacts on coral reefs, especially on reef fish larvae. I conducted my minor project under Jodie's supervision, and looked at the effects of increased suspended sediments on the gills of larval clownfish. I am now starting a PhD with Dr Rummer investigating the effects of suspended sediments on fish performance and ecosystem health. Email: <a href="mailto:sybille.hess@my.jcu.edu.au">sybille.hess@my.jcu.edu.au</a></p>
            <p><strong>Adam Habary (MSc, University of Copenhagen - 12 Mark, High Distinction)</strong> I earned my BSc. in general biology from the University of Southern Denmark, finishing with a research project investigating Harbour Porpoise (Phocoena phocoena) click differentiation. I later enrolled as a Cand. Scient. at the University of Copenhagen, studying marine biology. My research at James Cook University focused on the link between the optimal temperature for aerobic performance in coral reef fishes and their temperature preference.  I am almost ready to submit the story from my MSc research for peer review... watch this space! Email: <a href="mailto:adamhabary@hotmail.com">adamhabary@hotmail.com</a></p>
            <p><strong>Daniel Kraver (MSc, High Distinction - 2015)</strong> I'm originally from Connecticut and earned my BSc degree from Dickinson College in Carlisle, Pennsylvania in 2012. My research interests include ecology, physiology, and conservation of elasmobranchs and other highly exploited marine fishes. For my Master's research, I investigated the developmental & metabolic responses of epaulette shark (Hemiscyllium ocellatum) under environmental conditions associated with climate change. I currently have a paper in review involving this research. Watch this space! I am now employed as a Reef Resilience Coordinator for the coral reef conservation program at the Florida Department of Environmental Protection. Email:  <a href="mailto:Daniel.kraver@my.jcu.edu.au">Daniel.kraver@my.jcu.edu.au</a></p>
            <p><strong>Ian Silver-Gorges</strong> (undergraduate, SIT program 2014-2015) I am originally from Washington D.C., but am currently studying Biology at Oberlin College in Ohio. At JCU, I assisted with epaulette shark research and husbandry in the Rummer Lab. Previous experiences include assisting with research on deep reef fauna at the <a href="http://www.mnh.si.edu/">Smithsonian National Museum of Natural History</a> (<a href="http://ocean.si.edu/ocean-news/deep-reef-observation-project-drop">D.R.O.P. Project</a>, <a href="http://vertebrates.si.edu/fishes/fishes_staff_pages/baldwinc.cfm">Dr. Carole Baldwin</a>) and conducting estuarine fish research at <a href="http://wildlife.ohiodnr.gov/oldwomancreek">Old Woman Creek N.E.R.R.</a> (<a href="mailto:Kristin.Arend@dnr.state.oh.us">Dr. Kristin Arend</a>). Email: <a href="mailto:isilverg@oberlin.edu">isilverg@oberlin.edu</a></p>
            <p><strong>Stine Henriksen</strong> (Special Topics, Distinction 2014) I earned my BSc in Biology with a Minor in Ecology and Physiology from the University of Southern Denmark. I decided to do part of my Masters degree at James Cook University where I discovered my interest in Fisheries Science and Fish Physiology. My research interests involve sharks and how they cope with post-release stress. Email: <a href="mailto:fleckner86@hotmail.com">fleckner86@hotmail.com</a></p>
            <p>Katya Jay (undergraduate, SIT student) I am from Portland, Oregon, but am currently in my third year studying Biology and Geology at Macalester College in Minnesota. Previous and ongoing experience includes researching the evolutionary history and biogeography of a genus of leaf-litter arachnids from the Wet Tropics at Macalester College. I did a study abroad program in Australia through the School for International Training, and while with the Rummer Lab, I assisted with the mudskipper research. I am currently applying for PhD programs in the U.S. Email: <a href="mailto:kjay@macalester.edu">kjay@macalester.edu</a></p>
            <p><strong>Katherine Corkill</strong> (lab technician, 2014) Email: <a href="mailto:katherine.corkill@jcu.edu.au">katherine.corkill@jcu.edu.au</a></p>
            <p>Julia Peters (undergraduate) I am from New Jersey, USA, but am currently working towards a BSc in Environmental Science at Brown University in Rhode Island. My interest in marine biology & conservation stemmed largely from previous work at the Cape Eleuthera Institute in the Bahamas during my gap year where I was involved with a shark physiology study investigating the consequences of commercial fishing practices. Amongst other projects at JCU, I worked quite a bit with Connor on a study determining the metabolic costs of elevated temperatures in neonate epaulette sharks.  Email: <a href="mailto:julia_peters@brown.edu">julia_peters@brown.edu</a></p>
            <p>Martijn Johnson (MSc, Distinction - 2015) I earned my bachelors degree in applied science (majoring in fisheries) from University of Tasmania. My passion led me to Townsville to study tropical fish and fisheries. For my MSc in Marine Tropical Biology and Ecology, I explored the development of a tropical shark under future climate change conditions. I have a paper from this research currently in review. Watch this space!  I am currently employed by the <strong>Department of Primary Industries NSW</strong> Fisheries Resources Department.  Email: <a href="mailto:martijn.johnson@my.jcu.edu.au">martijn.johnson@my.jcu.edu.au</a></p>
            <p><strong>Andrew Corley (MSc, High Distinction - 2015)</strong> I earned my BA in Ecology and Evolutionary Biology from the University of Colorado.  Then, I worked as a SCUBA instructor for several years in Hawaii. My passion for tropical marine fauna brought me here to James Cook University where I focussed my interests on anthropogenic effects on coral reef-associated organisms. For my MSc, I examined the physiological consequences of long-term exposure to high carbon dioxide levels in reef fishes.  I am currently preparing this work to submit to a journal for peer-review.                                                          Email: <a href="mailto:andrew.corley@my.jcu.edu.au">andrew.corley@my.jcu.edu.au</a></p>
            <p><strong>Tiffany Nay (MSc, Distinction - 2015)</strong> I earned my BSc in Marine Biology from the University of West Florida while spending the summers in Wakatobi, Southeast Sulawesi, Indonesia assisting research on how crab-eating frogs and mudskipper fishes tolerate water loss and estimating metabolic rates in sea snakes. For my MSc research, I started investigating how/why fish utilize microhabitats with fluctuating water quality in coral reefs and mangrove ecosystems. You can also find me on <a href="https://twitter.com/TiffanyJNay">Twitter</a>. Email: <a href="mailto:tiffany.nay@my.jcu.edu.au">tiffany.nay@my.jcu.edu.au</a> Check out my recent paper <a href="http://br9xy4lf5w.scholar.serialssolutions.com/?sid=google&amp;auinit=TJ&amp;aulast=Nay&amp;atitle=Behavioural+thermoregulation+in+a+temperature-sensitive+coral+reef+fish,+the+five-lined+cardinalfish+(Cheilodipterus+quinquelineatus)&amp;id=doi:10.1007/s00338-015-1353-4&amp;title=Coral+reefs&amp;volume=34&amp;issue=4&amp;date=2015&amp;spage=1261&amp;issn=0722-4028">"</a><a href="http://br9xy4lf5w.scholar.serialssolutions.com/?sid=google&amp;auinit=TJ&amp;aulast=Nay&amp;atitle=Behavioural+thermoregulation+in+a+temperature-sensitive+coral+reef+fish,+the+five-lined+cardinalfish+(Cheilodipterus+quinquelineatus)&amp;id=doi:10.1007/s00338-015-1353-4&amp;title=Coral+reefs&amp;volume=34&amp;issue=4&amp;date=2015&amp;spage=1261&amp;issn=0722-4028">Behavioural thermoregulation in a temperature-sensitive coral reef fish, the five-lined cardinalfish (Cheilodipterus quinquelineatus)"</a>, which was published in the journal, Coral Reefs.</p>
            <p><strong>Connor Gervais (MSc - Distinction 2016, laboratory and field technician, 2016)</strong> I am originally from California and I earned my BSc in Marine Biology from the University of California, Santa Cruz. I earned my MSc (Distinction) here at JCU with the Rummer Lab where I explored the impact of elevated temeperatures on movement, behaviour, and growth in juvenile epaulette sharks (Hemiscyllium ocellatum). Over the next several months, I will be helping with various projects within the Rummer Lab and aim to start a PhD program next year. My research interests mainly relate to the impact climate change is having on marine organisms, especially elasmobranchs. I also have an ongoing collaboration with <a href="mailto:mporte26@fau.edu">Dr Marianne Porter</a> and her <a href="http://porterbiomechanics.wordpress.com">FAB Lab</a> at Florida Atlantic University.  Check out my recent paper: <a href="http://link.springer.com/article/10.1007/s12526-015-0429-2">"</a><a href="http://link.springer.com/article/10.1007/s12526-015-0429-2">Developing in warm water: Irregular colouration and patterns of a neonate elasmobranch"</a> which I published in <strong>Marine Biodiversity with <a href="https://johannmourier.wordpress.com/">Dr. Johann Mourier</a> and my supervisor, Dr. Jodie Rummer.</strong> Email: <a href="mailto:connor.gervais@my.jcu.edu.au">connor.gervais@my.jcu.edu.au</a> Follow me on <a href="https://twitter.com/walking_sharks">Twitter</a></p>
            <p>Dr Jacob Johansen (post-doc, intermittent 2014-2016) I am originally from Denmark where I earned my Bachelor's degree at Copenhagen University studying fish ecophysiology. I decided to escape the cold and move to Australia in 2005 where I earned my Master of Science (2007) and PhD (2013), both at James Cook University. I am interested in how commercially or ecologically important reef fishes tolerate adverse or extreme environmental conditions, and my specialities are whole organism performance metrics, e.g. energetics of swimming and behaviour.  I just finished a post-doc at the University of Florida in the Whitney Lab and am now based at the University of Texas at Austin working on oil spill impacts on commercially fished species. I have been a transient post-doc with #RummerLab for the past couple years. I also co-supervised Adam Habary and currently co-supervise Tiffany Nay. Email: <a href="mailto:jacob.johansen@utexas.edu">jacob.johansen@utexas.edu</a> <a href="https://scholar.google.com.au/citations?user=BtTdd18AAAAJ&amp;hl=en">Google Scholar Profile</a></p>
            <p><strong>Giverny Rodgers (PhD, 2016)</strong> Email: <a href="mailto:giverny.rodgers@my.jcu.edu.au">giverny.rodgers@my.jcu.edu.au</a> Originally from Adelaide, South Australia, I completed my BSc (Hons) at Flinders University. During my honours I worked on fisheries related projects and subsequently took on a position as a research assistant at the South Australian Research and Development Institute. In 2012 I moved to Townsville to start my PhD and James Cook University. This research concentrated on the effects of climate change relevant increases in temperature on coral reef fish from low-latitudes. I utilised a wide range of physiological measures including metabolic performance, enzyme activity, tissue histology and critical thermal limits to understand the potential for developmental and trans-generational acclimation of reef fish to environmental stressors. Outside of my research I am interested in science communication and outreach. I volunteer for various programs teaching science primarily to indigenous students in remote communities. I am  also a councillor for the <a href="https://www.google.com.au/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=1&amp;cad=rja&amp;uact=8&amp;ved=0ahUKEwi84uuajqHKAhXJG5QKHQvcAfgQFggbMAA&amp;url=http%3A%2F%2Fwww.australiancoralreefsociety.org%2F&amp;usg=AFQjCNHM2TC0NRt65ElCxDSJIqPwNTkrMQ&amp;sig2=_lVgeJwWTtcOtZOasRMmEQ&amp;bvm=bv.111396085,d.dGY">Australian Coral Reef Society</a>.</p>
            <p> Manon Amiguet (MSc, 2016) (based at <a href="http://www.criobe.pf/">Centre de Recherche Insulaire et Observatoire de </a><a href="http://www.criobe.pf/">l'Environnement (CRIOBE)</a> Papetoai, Moorea, Polynésie française) I am from south of France where I'm doing a master of science (MSc) at <a href="https://www.ephe.fr/">EPHE University</a> (Biodiversity and Environmental Management). During my previous internship I investigated demographics and behaviour in terrestrial species (e.g., birds and reptiles). This year, I was looking to investigate problems facing large marine predators. For this research, I have been working in Moorea at CRIOBE with Dr Jodie Rummer and Dr Serge Planes to determine the effect of climate change (e.g., elevated CO2 and temperature) on the physiology of juvenile black tip reef sharks. Email: <a href="mailto:manon.amiguet@gmail.com">manon.amiguet@gmail.com</a></p>
            
            <h2>Other</h2>
            <p>Fish drawings designed for Jodie Rummer by <a href="http://www.loggods.com/sci/index.php">Erin Walsh</a></p>
        </>
    )
}