
export const metadata = {
    title: "Collaborators",
    description: '',
}

export default function Collaborators() {
    return (
        <>
            <h1>Collaborators</h1>
            <h2>Oceania</h2>
            <p><a href="http://www.coralcoe.org.au/researchers/philip-munday">Prof. Philip Munday</a> (James Cook University, ARC CoECRS) <a href="http://www.griffith.edu.au/health/school-allied-health-sciences/staff/associate-professor-gillian-renshaw">Prof. Gillian Renshaw</a> (Griffiths University) <a href="http://data.aims.gov.au/staffcv/jsf/external/view.xhtml?partyId=100000064">Dr. Katharina Fabricius</a> (Australian Institute of Marine Sciences) <a href="http://A.Cheal@aims.gov.au">Dr. Alistair Cheal</a> (Australian Institute of Marine Sciences) <a href="https://scholar.google.fr/citations?user=ZneF9GQAAAAJ&amp;hl=en">Dr. Amelia Wenger</a> (James Cook University, ARC CoECRS) <a href="https://research.jcu.edu.au/portfolio/naomi.gardiner/">Dr. Naomi Gardiner</a> (James Cook University) <a href="https://research.jcu.edu.au/portfolio/morgan.pratchett/">Prof. Morgan Pratchett</a> (James Cook University, ARC CoECRS) <a href="http://www.coralcoe.org.au/?p=7149">Dr. Andy Hoey</a> (James Cook University, ARC CoECRS) <a href="http://www.coralcoe.org.au/postdocs/tracy-ainsworth-postdoctoral-fellow">Dr. Tracy Ainsworth</a> (James Cook University, ARC CoECRS) <a href="http://data.aims.gov.au/staffcv/jsf/external/view.xhtml?partyId=900004671">Dr. Timothy Clark</a> (Australia Institute of Marine Science, AIMS) <a href="http://www.bioscienceresearch.co.nz/phd-students/1051/fathima-iftikar/">Dr. Fatima Iftikar</a> (University of Auckland) <a href="https://unidirectory.auckland.ac.nz/profile/a-hickey">Prof. Anthony Hickey</a> (University of Auckland) <a href="http://www.csiro.au/Organisation-Structure/Flagships/Food-Futures-Flagship/FFF_People/Morash-Andrea.aspx">Dr. Andrea Morash</a> (Cambridge University, CSIRO, and University of Tasmania) <a href="http://www.owuscholarship.org/scholar/yoland-bosiger">Ms. Yoland Bosiger</a> (James Cook University, BBC Ocean) <a href="https://research.jcu.edu.au/portfolio/mark.mccormick/">Prof. Mark McCormick</a> (James Cook University, ARC CoECRS) <a href="http://www.coralcoe.org.au/researchers/sue-ann-watson">Dr. Sue-Ann Watson</a> (James Cook University, ARC CoECRS) <a href="http://www.criobe.pf/">Prof. Serge Planes</a> (Centre de Recherches Insulaire et Observatoire de l’Environnement (CRIOBE) Moorea, Polynésie française)</p>
            <h2>Europe</h2>
            <p><a href="http://christinecouturier.webs.com/">Dr. Christine Couturier</a> (University of Oslo, Norway) <a href="https://scholar.google.fr/citations?user=mvmRCecAAAAJ&amp;hl=en">Dr. Gabrielle Miller</a> (James Cook University, Australia & Oldenberg University, Germany) <a href="http://www.mn.uio.no/ibv/english/people/aca/gorann/">Prof. Göran Nilsson</a> (University of Oslo, Norway) <a href="http://johannmourier.wordpress.com/">Dr. Johann Mourier</a> (Universite de Perpignan, France & CRIOBE, Moorea, Polynésie française) <a href="http://www.gla.ac.uk/researchinstitutes/bahcm/staff/shaunkillen/">Dr. Shaun Killen</a> (University of Glasgow) <a href="http://www.mbl.ku.dk/JFSteffensen/">Prof. John Steffensen</a> (University of Copenhagen, Denmark) <a href="https://scholar.google.fr/citations?hl=en&amp;user=_HrIjR4AAAAJ&amp;view_op=list_works&amp;sortby=pubdate">Prof. David McKenzie</a> (Université Montpellier II), <a href="http://www.unifi.it/cercachi-per-134.html">Prof. Claudiu Supuran</a> (Università degli Studi di Firenze) <a href="http://www.liv.ac.uk/integrative-biology/staff/michael-berenbrink/">Dr. Michael Berenbrink</a> (University of Liverpool, UK) <a href="https://sites.google.com/site/sandraabinning/">Dr. Sandra Binning</a> (University of Neuchâtel, Switzerland) <a href="https://scholar.google.fr/citations?user=bXpyrNAAAAAJ&amp;hl=en">Dr. Dominique Roche</a> (University of Neuchâtel, Switzerland)</p>
            <h2>North America</h2>
            <p><a href="http://www.dixsonlab.com/"></a><a href="http://legacy.wlu.ca/homepage.php?grp_id=13895&amp;ct_id=4189&amp;f_id=1">Dr. Jonathan Wilson</a> (Wilfrid Laurier University, Canada & Ecofisiologia, CIMAR Porto Portugal) <a href="http://www.zoology.ubc.ca/person/randall">Prof. David Randall</a> (City University Hong Kong, University of British Columbia) <a href="http://www.dixsonlab.com/">Dr. Danielle Dixson</a> (Georgia Institute of Technology) <a href="https://scripps.ucsd.edu/labs/mtresguerres/members/martin-tresguerres/">Dr. Martin Tresguerres</a> (Scripps Institution of Oceanography, University of California at San Diego) <a href="http://brauner-home.zoology.ubc.ca/">Prof. Colin Brauner</a> (University of British Columbia) <a href="http://people.landfood.ubc.ca/anthony.farrell/index.html">Prof. Tony Farrell</a> (University of British Columbia) <a href="https://swfsc.noaa.gov/staff.aspx?id=590">Dr. John Hyde</a> (National Oceanic and Atmospheric Administration, USA) <a href="https://sites.google.com/site/maudcoferrari/">Prof. Maud Ferarri</a> (University of Saskatchewan) <a href="http://www.whitney.ufl.edu/welcome-dr-jacob-johansen/">Dr. Jacob Johansen</a> (University of Florida, Whitney Laboratory for Marine Bioscience) <a href="http://www.uaa.alaska.edu/biological-sciences/faculty-and-staff/stecyk.cfm">Dr. Jonathan Stecyk</a> (University of Alaska, Anchorage) <a href="http://www.neaq.org/conservation_and_research/projects/project_pages/elasmobranch_mortality_and_stress_physiology.php">Dr. John Mandelman</a> (John H. Prescott Marine Laboratory, New England Aquarium) <a href="http://www.vims.edu/people/brill_rw/index.php">Dr. Rich Brill</a> (Virginia Institute of Marine Science, NOAA)</p>
            <h2>Asia</h2>
            <p><a href="http://yuyangshuhong@hotmail.com">Prof. Shuhong Wang</a> (University of Jimei, China)</p>
        </>
    )
}
